### ISSUE TITLE
getTargetFilename() error

### ISSUE THREAD

**Issue by tazzkiller** [delight-im/PHP-FileUpload#5]
If withTargetFilename() is not set on upload, getTargetFilename() don't return the random name generated

**Comment by ocram** [comment]
Thank you!

This is actually expected and desired behavior, but perhaps poorly documented.

You could call `save` twice on the same instance and it would upload with two different random names that are generated at the time when the actual upload is requested, not when the upload is described initially. So what it returns is only the filename you have set yourself (explicitly). Thus it also allows you to check *if* you have already set a name.

We could change this behavior, but I’m not sure if that’s really necessary.

Why would you need the random file name even before the upload has been processed? As shown in the README, it’s easy to get the generated name as soon as it has actually been created:

```php
$uploadedFile = $upload->save();
$generatedRandomName = $uploadedFile->getFilenameWithExtension();
```

**Comment by ocram** [comment]
No need for any changes here
