### ISSUE TITLE
Getting Delight\FileUpload\Throwable\TargetFileWriteError

### ISSUE THREAD

**Issue by ghost** [delight-im/PHP-FileUpload#6]
I am getting the throwable error TargetFileWriteError. Is this something to do with my server settings?

Here is my image upload code:

    $checkProfileImg = $db->selectValue('SELECT user_profileimage FROM users WHERE id = ?',[$user_id]);
    $uploadPath = "/images/user-uploads/images";
    $upload = new \Delight\FileUpload\FileUpload();
    $upload->withMaximumSizeInKilobytes(1000);
    $upload->withAllowedExtensions([ 'jpeg', 'jpg', 'png', 'gif' ]);
    $upload->withTargetDirectory($uploadPath);
    $upload->from('image');

    if(strlen($checkProfileImg) === 0) {
        // If new person, reset to random string
        $checkProfileImg = randString("95", "0123456789abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ");
    }

    $upload->withTargetFilename($checkProfileImg);

    try {
        $upload->save();
        $GLOBALS['JSONresponse']['status'] = "success";
        $GLOBALS['JSONresponse']['message'] = "profile image updated";
        $GLOBALS['JSONresponse']['data']['image'] = $checkProfileImg;
        refreshData();
    }
    catch (\Delight\FileUpload\Throwable\InputNotFoundException $e) {
        // input not found
        $GLOBALS['JSONresponse']['message'] = "image not found";
    }
    catch (\Delight\FileUpload\Throwable\InvalidFilenameException $e) {
        // invalid filename
        $GLOBALS['JSONresponse']['message'] = "invalid file name";
    }
    catch (\Delight\FileUpload\Throwable\InvalidExtensionException $e) {
        // invalid extension
        $GLOBALS['JSONresponse']['message'] = "invalid extension";
    }
    catch (\Delight\FileUpload\Throwable\FileTooLargeException $e) {
        // file too large
        $GLOBALS['JSONresponse']['message'] = "image too large";
    }
    catch (\Delight\FileUpload\Throwable\UploadCancelledException $e) {
        // upload cancelled
        $GLOBALS['JSONresponse']['message'] = "update cancelled";
    }

**Comment by ocram** [comment]
This usually means that the directory `/images/user-uploads/images` does neither exist nor can it be created.

What operating system are you running this on?

Is that (absolute) path really what you want? Or do you want it relative to your app’s folder or the folder of the current script?

Perhaps try something like this?

```php
$uploadPath = __DIR__ . "/images/user-uploads/images";
// or
$uploadPath = __DIR__ . "/../images/user-uploads/images";
// etc.
```

**Comment by ghost** [comment]
That worked. Thank you! I wasn't paying attention when i set the absolute path. You've made an awesome plugin!!

**Comment by ocram** [comment]
Glad to hear that, thanks for your appreciation!
