### ISSUE TITLE
How to go back when setting a directory

### ISSUE THREAD

**Issue by brahimbjz** [delight-im/PHP-FileUpload#7]
Hello, I am using the library in a subdomain (admin.example.com) and **I want to store the files in the public folder** (public_html), but for this **I must go back at least one directory** backwards, and I have tried this but it doesn't work:

`$upload->withTargetDirectory('/../public_html/uploads/');`

How could I do it correctly? (Sorry for the translator's English)

**Comment by ocram** [comment]
Thanks for your question!

It’s great that you seem to have solved the issue. Could you perhaps share your solution here so others with the same problem can find help in the future?

Thank you!

(Your English is perfect.)

**Comment by brahimbjz** [comment]
Yes, thank you very much for responding.

I just had to remove the first slash. I replaced the above code with:

`$upload->withTargetDirectory('../public_html/uploads/');`

And it works perfectly, greetings.

**Comment by ocram** [comment]
That’s good to see. Thank you!
