### ISSUE TITLE
undefined method Delight\FileUpload\File::getFilenameExtension()

### ISSUE THREAD

**Issue by beshoo** [delight-im/PHP-FileUpload#8]
$upload = new \Delight\FileUpload\FileUpload();
$uploadedFile = $upload->save();
$uploadedFile->getFilenameExtension();

>> undefined method Delight\FileUpload\File::getFilenameExtension()

but if i prent_r($uploadedFile); i can see the extention in the protected opject.

**Comment by beshoo** [comment]
```

(
--
  | [directory:Delight\FileUpload\File:private] => Delight\FileUpload\Directory Object
  | (
  | [path:Delight\FileUpload\Directory:private] => /home/mymujeeb/public_html/api/../uploads
  | )
  |  
  | [filename:Delight\FileUpload\File:private] => 1596852405
  | [extension:Delight\FileUpload\File:private] => jpg
  | )


```

**Comment by beshoo** [comment]
it works only with base64 upload but not with a normal file upload.

**Comment by ocram** [comment]
Thanks!

The method `getFilenameExtension` is defined on `FileUpload` and its subclasses, whose instances are often called `$upload` in the README. This is your “upload manager” and you can define and read again the extension that you want.

What you want is defined on `File`, whose instances are usually called `$uploadedFile` in the README. There, the method is called just `getExtension`.

Does that help?

If it does, the README should certainly be improved to make this clear.

**Comment by beshoo** [comment]
` $uploadedFile->getExtension();` Works as expected. Please updatw the doc

**Comment by ocram** [comment]
Glad to hear that!

The purpose of the wrong methods has now been clarified in the README in https://github.com/delight-im/PHP-FileUpload/commit/69f1f968fc15453bc6422ab80247d2938317d196 and the correct methods have been added to the documentation in https://github.com/delight-im/PHP-FileUpload/commit/6c5924862b6692952db831c10face7ad2e935f1c. Apart from that, we will rename the wrong methods in a future major release, as is now tracked in https://github.com/delight-im/PHP-FileUpload/issues/9.

Thanks again!
